---
- name: Load variables for libvirt tasks
  include_vars: settings.yaml

- name: Install libvirt packages
  include_role:
    name: parts/libvirt

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups:
      - libvirt
    append: true
- name: reset ssh connection to allow user changes to affect
  meta: reset_connection
- name: Restore a libvirt snapshot
  when: restore_snapshot
  vars:
    ansible_become: true
    snapshot_restore: true
  include_role:
    name: snapshot-libvirt

- name: Update zuul inventory
  when: restore_snapshot|bool
  vars:
    libvirt_nodepool: true
    working_dir: "{{ install_path }}"
    non_root_user: "{{ ansible_user }}"
    non_root_group: "{{ ansible_user }}"
    libvirt_wait_delay: 20
    libvirt_wait_retries: 3
    libvirt_volume_pool: oooq_pool
    ansible_become: true
  block:
    - set_fact:
        local_working_dir: "{{ install_path }}/etc_zuul"

    - include_role:
        name: libvirt/setup/overcloud
        tasks_from: eval_subnode_ips
      with_items: "{{ overcloud_nodes }}"

    - include_role:
        name: libvirt/setup/overcloud
        tasks_from: zuul_multinode_inventory

- name: Setup libvirt nodes
  when: not restore_snapshot
  vars:
    libvirt_nodepool: true
    local_working_dir: "{{ install_path }}"
    working_dir: "{{ install_path }}"
    non_root_user: "{{ ansible_user }}"
    non_root_group: "{{ ansible_user }}"

  block:
    - name: Start nodes
      block:
        - name: Tear down nodes
          include_role:
            name: libvirt/teardown/nodes

        - name: Set up nodes
          include_role:
            name: libvirt/setup/overcloud

        - name: Set up tripleo inventory
          include_role:
            name: tripleo-inventory

    - name: prepare nodes
      # We call playbook to parallelize
      shell: |
        set -e
        PATH=$PATH:$HOME/.local/bin
        ANSIBLE_STDOUT_CALLBACK=debug
        ansible-playbook -i {{ install_path }}/hosts -vv \
          {{ role_path }}/tasks/libvirt/prepare.yaml
    - name: Create libvirt snapshot
      when: create_snapshot
      vars:
        ansible_become: true
        snapshot_create: true
      include_role:
        name: snapshot-libvirt
