---

- hosts: primary
  tasks:
    - name: Gather needed facts
      setup:
        gather_subset: "!min,user_dir,distribution"
      when:
        - ansible_user_dir is not defined
        - ansible_distribution is not defined

    - when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int == 7
      become: true
      block:

        - name: Install RDO repos for getting packages for CentOS 7
          yum:
            name: https://www.rdoproject.org/repos/rdo-release.rpm

        - name: Update Git to v2 in CentOS 7 - remove old git
          yum:
            name: git
            state: absent

        - name: Update Git to v2 in CentOS 7 - install repo
          yum:
            name: https://repo.ius.io/ius-release-el7.rpm

        - name: Update Git to v2 in CentOS 7 - install git
          yum:
            name: git224


    - name: Check if pip is installed
      shell: command -v pip > /dev/null 2>&1
      ignore_errors: true
      changed_when: false
      register: pip_exists

    - when: pip_exists.rc != 0
      name: Install pip
      block:
        - when: ansible_distribution == "CentOS"
          name: Install EPEL
          become: true
          package:
            name: epel-release
        - name: Install pip
          become: true
          package:
            name:
              - python{{ '3' if ansible_distribution_major_version|int == 8 else '' }}-pip

    # reproducer_role_top_dir evaluates to "reproducer_role_top_dir":
    - name: Set fact reproducer_role_top_dir
      set_fact:
        reproducer_role_top_dir: >-
          {{ reproducer_role_top_dir | default(playbook_dir + '/../..') }}

    - name: Print top dir
      debug:
        var: reproducer_role_top_dir

    # Adding when to this command for linting error
    # https://github.com/ansible/ansible-lint/issues/165
    # Pipe true because bindep always returns code 1 (error)
    # when packages are missing
    - name: Discover packages that are not installed
      shell: |
        export PATH=$PATH:$HOME/.local/bin/
        bindep -b -f {{ reproducer_role_top_dir }}/bindep.txt
      register: package_list
      failed_when: false
      changed_when: false

    - name: Install rpms from bindep
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ package_list.stdout_lines }}"
