---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for mysql to become ready
      wait_for:
        host: mysql
        port: 3306
        state: started
        delay: 5
        connect_timeout: 15
        timeout: 30
